### ISSUE TITLE
Chapter 3 Stuck Issue

### ISSUE THREAD

**Issue by ianterrell** [erikamaker/pickaxe#3]
Just as a teaser I'll say that with only minor changes I got it running:

```
❯ ruby stock_stats.rb data.csv
Processing data.csv
Total value = 122.07
```

:)

Okay, now... in its current state, I reproduce your error:

```
❯ ruby stock_stats.rb data.csv
stock_stats.rb:1:in `require_relative': cannot load such file -- /Users/ian/src/erika/pickaxe/chapter_3/csv_reader (LoadError)
	from stock_stats.rb:1:in `<main>'
```

The overarching lesson here is to read all error messages very carefully and make sure you understand them. 

This is non-trivial, and some languages have better error messages than others, and some specific cases are more clear than others, and it is a skill in itself that needs practice — but overall the lesson holds very strongly. I cannot count the number of times I've been asked for help (by people with years of experience) and both the problem and the solution are right in front of them in the form of an error message.

So we know:

- problematic file: `stock_stats.rb`
- line number of error: 1
- method reporting error: `require_relative'
- error class: `LoadError`
- error message: `cannot load such file -- .../csv_reader`
- stack trace: `from...` (will make more senes later)

So that line of code is:

```ruby
require_relative "csv_reader"
```

Not a lot to work with! And, well, it looks verbatim from the book:

<img width="256" alt="Screenshot 2023-02-19 at 9 35 25 AM" src="https://user-images.githubusercontent.com/54963/219954878-fda38c82-cb61-4f67-a458-9be9d68ec4be.png">

I suppose here is another macro lesson. If something is not working but the code is right, _something else is wrong_. Sometimes at work something will work for one person but not for another person. The code is identical. The question becomes: "What is different about our setups?"

It's also reasonable to look into official documentation. We're working with `require_relative`, so...

https://ruby-doc.org/3.2.1/Kernel.html#method-i-require_relative

> Ruby tries to load the library named string relative to the directory containing the requiring file. If the file does not exist a [LoadError](https://ruby-doc.org/3.2.1/LoadError.html) is raised. Returns true if the file was loaded and false if the file was already loaded before.

Well, that doesn't help tremendously, but maybe a little. First, we learn that it has a return value, which I've never ever thought about, so now I know a tiny bit more. And we see that it raises a `LoadError`, which is what we're observing, so it seems like things are internally consistent. And finally it says "load the library", where I might note that "library" is not exactly "filename."

We see that it raises a `LoadError` "if the file does not exist." That makes me want to check: does the file exist? We can list all files in our current directory with `ls` from the command line (as I'm sure you know). I'll use the "long format" with the `-l` option (bonus points: run `man ls` for "show me the manual for the command `ls`", the official documentation for *NIX commands).

```
❯ ls -l
total 64
-rw-r--r--  1 ian  staff    182 Feb 19 09:29 book_in_stock .rb
-rw-r--r--  1 ian  staff  12406 Feb 19 09:05 ch3_notes.md
-rw-r--r--  1 ian  staff    686 Feb 19 09:29 csv_reader .rb
-rw-r--r--  1 ian  staff    140 Feb 19 09:29 data.csv
-rw-r--r--  1 ian  staff    227 Feb 19 09:05 stock_stats.rb
```

So... inspecting very carefully... What is `require_relative` expecting as a "library"? How is it converting it to a filename? And then... does the file exist?

Computers are very literal.

**Comment by erikamaker** [comment]
> So we know: ... 

I think I understand the error message correctly. I was able to intuit most of what you listed. 

> The code is identical. The question becomes: "What is different about our setups?"

I had considered maybe the file path was different, but `ls` in the file showed me they're all there. 

I also considered that it's broken BECAUSE the code is identical. I wondered what parts need to be changed if it's just boilerplate names that I should be filling with real ones. But, when I change the `csv_file_name` to `data.csv`, that doesn't help. 

And anyway, the error is for line 1 anyway. I can't figure out what could be wrong here. 

`require_relative "csv_reader.rb"`

I've changed it to use single quotes, used parentheses, removed the extension, added a space between the file name and the extension, and... well, probably a bunch of other panicky and random shots in the dark. 

I realized the file was saved as "csv_reader .rb" with a typo space separating the extension and the name. But, that didn't really fix the issue. The error changed, but it's still happening at line 1. 

```
erikamaker@erikas-computer:~/pickaxe/chapter_3/books_in_stock$ ruby stock_stats.rb data.csv 
stock_stats.rb:1:in `require_relative': --> /home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb
syntax error, unexpected string literal, expecting ')'
   4  class CsvReader
>  9    def read_in_csv_data('data.csv')               
> 13    end
  25  end
/home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb:9: syntax error, unexpected string literal, expecting ')' (SyntaxError)
  def read_in_csv_data('data.csv')               
                       ^
/home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb:25: syntax error, unexpected `end'
	from stock_stats.rb:1:in `<main>'

```

But, there is also an error on line 9 of csv_reader.rb now. 

1.) I tried changing the argument for `require_relative` on line 1. To me, it looked like the error meant it wanted a parantheses-wrapped name. 
    - Changing it to ("csv_reader.rb") or ('csv_reader.rb') or (csv_reader.rb) didn't change anything. 
    
2.) I can't find the syntax error that csv_reader.rb threw at line 25.
    - I wonder if it has anything to do with the stock_stats.rb file not being correct? 
    - Currently, stock_stats.rb's first line hasn't changed. I've reverted back it after trying different syntaxes / names. 
    

> What is require_relative expecting as a "library"? How is it converting it to a filename? And then... does the file exist?

I feel like my hair is starting to burn, haha. I'm thinking pretty hard about this, and I have come up with these truths: 

1.) In the `csv_reader.rb` file, the "library" it's expecting is `book_in_stock.rb`. 
2.) That file exists in the same directory as the others. 
3.) I have it listed as an `.rb` file in the directory, and in the first line of `book_in_stock.rb`. 

I want to probe a little bit, but I'm not throwing in the towel (yet!): 

- Is it a syntax issue? I feel like everything exists as it should in the directory.
- Am I requiring the libraries incorrectly? I tried documentation syntax (for example): 

`require_relative 'book_in_stock` 

And, side note: 

- Do I need to rename the parts of `csv_reader.rb` that look like boilerplate code (ie `csv_file_name`)? My guess is that, yes, of course I would.

**Comment by ianterrell** [comment]
> I feel like my hair is starting to burn, haha. 

Totally normal. :) I think the world would have more programmers if sitting with bugs didn't cause such mental anguish sometimes. There's a sense that _it should be working_ according to your understanding, and our brains are so wired to think our understandings are correct, so it feels crazy making.

> I realized the file was saved as "csv_reader .rb" with a typo space separating the extension and the name. But, that didn't really fix the issue. The error changed, but it's still happening at line 1.

No no no — it **did** fix the issue. _This issue_. You just happen to have multiple issues. :)

That is also a super common pattern in programming. You fix one thing only to uncover another. One pattern is to only add a little bit at a time, testing as you go (I think the book will cover automated testing eventually, chapter 13). An insight is: if you add ten lines to your program and it is now broken, which one did it? Contrast with: if you add one line to your program and it is now broken, which one did it?

> I've changed it to use single quotes, used parentheses, removed the extension, added a space between the file name and the extension, and... well, probably a bunch of other panicky and random shots in the dark.

This is a habit I would encourage you to break. (I still see people a decade into their career doing it.) _Experimenting_ is slightly different and can be positive. I think the difference is: are you creating a hypothesis that is testable that helps validate or invalidate a mental model of what's happening? Or are you frustrated and trying to make the damn thing run? One can be net positive; the other _can_ be if you can after the fact turn it into an experiment, but it probably has negative side effects on average.

There's a useful concept related to the insight about adding many lines of code and wondering which one breaks your program, and that is the minimal reproducible test case. What is the least amount of code you can write that reproduces what you see?

Here's where you're at currently:

```
❯ ls
book_in_stock .rb ch3_notes.md      csv_reader .rb    data.csv          stock_stats.rb
❯ ruby stock_stats.rb data.csv
stock_stats.rb:1:in `require_relative': cannot load such file -- /Users/ian/src/erika/pickaxe/chapter_3/csv_reader (LoadError)
	from stock_stats.rb:1:in `<main>'
```

Here is a teensy tiny portion of that, just one empty file. `cat` is a command to "concatenate and print files", so it shows the contents of `stock_stats.rb`:

```
❯ ls
stock_stats.rb
❯ cat stock_stats.rb
❯ ruby stock_stats.rb data.csv
❯ 
```

Okay, so the empty file runs without an error! Now let's add the require statement.

```
❯ ls
stock_stats.rb
❯ cat stock_stats.rb
require_relative "csv_reader"
❯ ruby stock_stats.rb data.csv
stock_stats.rb:1:in `require_relative': cannot load such file -- /Users/ian/src/erika/pickaxe/chapter_3_repro/csv_reader (LoadError)
	from stock_stats.rb:1:in `<main>'
```

Okay, so now with the one single line `require_relative "csv_reader"` it fails, with the same error you originally see. The file doesn't exist! Only this time, we know it doesn't exist, because, well, we made sure it doesn't exist. So let's make it exist, with the space in the filename.

```
❯ ls
csv_reader .rb stock_stats.rb
❯ cat stock_stats.rb
require_relative "csv_reader"
❯ cat csv_reader\ .rb
❯ ruby stock_stats.rb data.csv
stock_stats.rb:1:in `require_relative': cannot load such file -- /Users/ian/src/erika/pickaxe/chapter_3_repro/csv_reader (LoadError)
	from stock_stats.rb:1:in `<main>'
```

Okay, now let's remove the space...

```
❯ ls
csv_reader.rb  stock_stats.rb
❯ ruby stock_stats.rb data.csv
❯ 
```

It runs, no error!

So from that exercise we see that _that particular issue_ was entirely caused by the space.

> I've changed it to use single quotes, used parentheses, removed the extension, added a space between the file name and the extension, and... well, probably a bunch of other panicky and random shots in the dark.

Back to experimentation and models. Programming is, say, the creation of a model of some real world stuff, like the OOP idea of classes representing things and processes in the world. But then there is your own mental model of the programming model. One task of the programmer is to refine their mental model of what's happening in the software.

So the homework questions coming out of your shots in the dark are:

- As a part of the language, what is `require_relative`?
- As a part of the language, what is `"csv_reader"`? What is it when used with `require_relative`?
- What's the difference between using single quotes and double quotes?
- What's the difference between using parentheses or not?
- Are extensions necessary when calling `require_relative`? Can you use them if you want?
- Could you fix the `LoadError` without renaming the file?

You can ignore all of that if you like. But that is the depth of thought I like to encourage. Even tiny bugs are huge learning opportunities. 

For the record, I had guesses about the last two but wasn't 100% positive, so I experimented myself! I've worked with a lot of people who will speculate and postulate when all they really need to do is write 3 lines of code and confirm.

Okay, back to your original code, with the typo space removed.

> I realized the file was saved as "csv_reader .rb" with a typo space separating the extension and the name. But, that didn't really fix the issue. The error changed, but it's still happening at line 1.
> ...
> But, there is also an error on line 9 of csv_reader.rb now.

I think this is clear from all of the above and please forgive me for repeating myself. The error didn't change, there is a new error. This error is not "happening" at line 1 so much as it is "originating" at line 1.

The error is:

```
stock_stats.rb:1:in `require_relative': --> /home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb
syntax error, unexpected string literal, expecting ')'
```

Note the "in" after the line 1, and the arrow. It is saying that "After calling `require_relative`, I had an error parsing the syntax of the file that was required. Here are the details of that error."

Being able to decipher these error messages takes knowledge and practice and experience. This is a natural part of building it. And, fun on top of fun, it's an experience you get to repeat with every new language you learn.

> 1.) I tried changing the argument for require_relative on line 1. To me, it looked like the error meant it wanted a parantheses-wrapped name.
> - Changing it to ("csv_reader.rb") or ('csv_reader.rb') or (csv_reader.rb) didn't change anything.

Error messages are often confusing, because the interpreter can only interpret what is there, not necessarily what you meant. _And_ errors can cascade which can make things confusing.

This is the important part of that error message:

```
syntax error, unexpected string literal, expecting ')'
   4  class CsvReader
>  9    def read_in_csv_data('data.csv')               
> 13    end
  25  end
/home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb:9: syntax error, unexpected string literal, expecting ')' (SyntaxError)
  def read_in_csv_data('data.csv')               
                       ^
```

That is trying to point you to the line and the column of the error, with the message and the arrows. Note that the arrows triangulate the error to `'data.csv'`.

The `expecting ')'` part makes sense when you understand what the interpreter is trying to do and how the parser works, but that's a lot to explain right now. :) The easier part is `unexpected string literal`.

So the questions to ask and answer and internalize are:

- What is a string literal?
- Where am I using the string literal?
- Can I put a string literal where it currently is?
- What is supposed to go where it currently is?

As maybe a further hint, compare the differences between:

```ruby
def valid_method(arg)
  # body
end

valid_method("value")

def invalid_method("value")
  # body
end
```

I will also warn you that... you have a few more errors to work through after you work through that one. I believe you can do it, and won't solve the Ruby ones for you here. I will note that if you get to this point:

```
<internal:kernel>:173:in `Float': can't convert nil into Float (TypeError)
	from /Users/ian/src/erika/pickaxe/chapter_3/book_in_stock.rb:6:in `initialize'
```

That it's not an issue with your Ruby code but with your CSV file. I can say more later if you like.

Final notes:

> Do I need to rename the parts of csv_reader.rb that look like boilerplate code (ie csv_file_name)? My guess is that, yes, of course I would.

No guessing! Assuming you mean, say:

```ruby
ARGV.each do |csv_file_name|
  $stderr.puts "Processing #{csv_file_name}"
  reader.read_in_csv_data(csv_file_name)
end
```

Then you have more homework questions.

- As a part of the language, what is `csv_file_name` there?
- What is it relative to `ARGV.each`?
- If you rename it, what would you rename it to?
- If you rename it, what would happen and why?

Good luck! You can do it!

**Comment by erikamaker** [comment]
> I think the world would have more programmers if sitting with bugs didn't cause such mental anguish sometimes. 

Cognitive dissonance makes my soul itchy. Gross. 

> What is a string literal?

A string literal is a string of text, like "abc", or 'abc'. 

> As a part of the language, what is require_relative?

This requires a file from the same directory as the file that calls it. 

> Where am I using the string literal? Can I put a string literal where it currently is?

Where the filename that's being required is expected.

> Can I put a string literal where it currently is?

I think not. It would be the filename itself. 

I'm chipping away at this but I keep running into errors. 

What is supposed to go where it currently is?

The file that's being referenced. 

> As a part of the language, what is "csv_reader"? What is it when used with require_relative?

"csv_reader" is the name of the file that's being required. 

> What's the difference between using single quotes and double quotes?

Singles are used for strings typically, and double for interpolating or escape sequence (like "\n") 

> What's the difference between using parentheses or not?

Parentheses are usually used to make parameters more legible, or to separate multiple expressions. To me, the "expecting (" error line now sounds like a red herring, arising because of another issue in the csv_reader.rb file, where something is expected that wasn't provided by it. 

> Are extensions necessary when calling require_relative? Can you use them if you want?

After reading more about it, I do not need the extension as part of the filename argument. However, adding it is also acceptable. 

> Could you fix the LoadError without renaming the file?

It doesn't appear to fix it, no. But, I found that changing something else at least _changes_ the error. 


I realized that Ruby has good library for CSV files. That makes me feel like I shouldn't have messed with the first line `require "csv"` in csv_reader.rb to begin with. I think now that this is just how the CSV library was required, and shouldn't have been `"data.csv`" like I was trying. Calling in the data file happens later where the line starts `csv_file_name`. 

Changing the first line of csv_reader.rb back to `require "csv"` gave me a whole new error, so I think I'm on the right track. 


```
<internal:kernel>:173:in `Float': can't convert nil into Float (TypeError)
	from /home/erikamaker/pickaxe/chapter_3/books_in_stock/book_in_stock.rb:6:in `initialize'
	from /home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb:11:in `new'
	from /home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb:11:in `block in read_in_csv_data'
	from /home/erikamaker/.rbenv/versions/3.2.1/lib/ruby/3.2.0/csv.rb:2557:in `each'
	from /home/erikamaker/.rbenv/versions/3.2.1/lib/ruby/3.2.0/csv.rb:1334:in `block in foreach'
	from /home/erikamaker/.rbenv/versions/3.2.1/lib/ruby/3.2.0/csv.rb:1610:in `open'
	from /home/erikamaker/.rbenv/versions/3.2.1/lib/ruby/3.2.0/csv.rb:1333:in `foreach'
	from /home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb:10:in `read_in_csv_data'
	from stock_stats.rb:7:in `block in <main>'
	from stock_stats.rb:5:in `each'
	from stock_stats.rb:5:in `<main>'
```

I'm digging around a little right now to understand what these error messages mean, so I can track the bug further. Thanks for indulging my slow process! Open to any thoughts or pointers. At this point, I think I'm going to have to be on Chapter 3 through the rest of the week.

**Comment by ianterrell** [comment]
Hey, if you're at the `nil into Float` issue then you're almost there! I think that's the last thing I ran into when tweaking your program. The fix here is... not straightforward.

<details>
  <summary>Here's the fix</summary>
  A CSV is formatted like so:

```csv
header1,header2
a1,a2
b1,b2
```

But yours is formatted like:

```csv
header1,header2
a1,a2
b1,b2

```

You just have one extra empty line. The file may have a single "trailing line break", so that it ends in `\n`, but yours ends in `\n\n`. So it thinks that empty line is data, and reads it as `nil, nil`, which you then try to convert to a float...
</details>

>>What is a string literal?
>
>A string literal is a string of text, like "abc", or 'abc'.

Yes — to contrast with "variable". `a = 'a'`, `a` is a string variable and `'a'` is a string literal. 

(Simple, and you know it, but helpful to recall when parsing error messages).

>> As a part of the language, what is require_relative?
>
> This requires a file from the same directory as the file that calls it.

I'm obtuse and don't know how to necessarily guide, but what I was trying to get you to think about was... it's a method!

You wrote this:

> I've changed it to use single quotes, used parentheses, removed the extension, added a space between the file name and the extension, and... well, probably a bunch of other panicky and random shots in the dark.

But `require_relative` is just a method, and in Ruby you know you can use parentheses or not. And it takes a string parameter, and you know that in Ruby you can use single quotes or double quotes. So some of the thing you tried you could have predicted the outcome of because you know how it works. 

```ruby
require_relative 'a'
require_relative('a')
require_relative "a"
require_relative("a")
```

It was just another stab at pointing you toward... narrowing down where you would look for a solution.

>> Where am I using the string literal?
>
> Where the filename that's being required is expected.
>
>>Can I put a string literal where it currently is?
>
> I think not. It would be the filename itself.
>
>>What is supposed to go where it currently is?
>
> The file that's being referenced.

The error in context was:

```
syntax error, unexpected string literal, expecting ')'
   4  class CsvReader
>  9    def read_in_csv_data('data.csv')               
> 13    end
  25  end
/home/erikamaker/pickaxe/chapter_3/books_in_stock/csv_reader.rb:9: syntax error, unexpected string literal, expecting ')' (SyntaxError)
  def read_in_csv_data('data.csv')               
                       ^
```

In this case, `read_in_csv_data` is a method. And in context here, `def read_in_csv_data` is a _method definition_. When you define a method you describe the arguments it takes, in the form of _argument variables_. 

```ruby
def method('literal')
  # ???
end
```

As a method definition, that doesn't make sense! In the body, how would you reference the `'literal'` thing there? When you call it... what would you call it with? Rather, as you know, you define it as a variable, so that you can reference it inside the body, and substitute a value in when you call it.

```ruby
def method(argument)
  do_something_with argument
end

method('call it with a literal, sure')
```

I know you know all that, I'm just writing it down to talk through it in case any part is helpful. There's one thing that might be most helpful in tying all of these things together. The error is:

```
syntax error, unexpected string literal, expecting ')'
```

And of that, perhaps the actual most important part is the first two words: **syntax error**.

You know syntax vs semantics in English, and the same is true of programming languages. A syntax error means: "This isn't valid Ruby!" It's not that you're using something wrong, it's that _the code itself isn't valid as code_. That narrows down your search space considerably when thinking these things through.

> To me, the "expecting )" error line now sounds like a red herring, arising because of another issue in the csv_reader.rb file, where something is expected that wasn't provided by it.

In case it's helpful in building up a mental model, or you run into it again, the error is about this line:

```ruby
def read_in_csv_data('data.csv')     
```

Ruby reads this in one character at a time, like, `d`,`e`,`f`,` `,`r`,`e`,`a`... At each step it tries to figure out what you mean. When it reads `def` it says, "oooh, I'm defining a method! I know what comes next: the method name!" And those have certain rules, which you follow, and then it reads at the end of the method name `a`,`t`,`a`,`(` — and when it sees `(` it says, "Alright, now I know the method name, it ended before the `(`, so what comes next is either an argument variable or `)`". And then you give it neither, and the error it happens to print out is "But I was looking for `)`!".

>> Could you fix the LoadError without renaming the file?
>
> It doesn't appear to fix it, no. But, I found that changing something else at least changes the error.

With your filename as `csv_reader .rb` you could actually load the file with the space. `require_relative "csv_reader "`. 😆 Probably the right fix as it disobeys convention, but hey!

> so I think I'm on the right track.

You are!

**Comment by erikamaker** [comment]
> You just have one extra empty line. 

I think I know when that happened! I was thumbing through that file trying to learn more about it, and must have inadvertently added a row.

> what I was trying to get you to think about was... it's a method!
> It was just another stab at pointing you toward... narrowing down where you would look for a solution

I now have the correct output :D 

```
rb data.csv 
Processing data.csv
Total value = 122.07
``` 

> And of that, perhaps the actual most important part is the first two words: syntax error.

I felt like I knew what each component was supposed to do, and couldn't figure out what was missing. I just didn't have the correct grammar holding those components together. 

> With your filename as csv_reader .rb you could actually load the file with the space. 
> Probably the right fix as it disobeys convention, but hey!

A bonus! :D

**Comment by erikamaker** [comment]
BTW: I'll be finishing Chapter 3 tonight and probably will have that up tomorrow morning. Sorry I've fallen behind a bit! That bug frustrated me, but I didn't want to rely on getting the answer too quickly. I sat on it for a little bit. 

By the way, how did you know the CSV file had the extra line?

**Comment by ianterrell** [comment]
> I now have the correct output :D

Congrats! 🎉 

That's a pretty big win — there were lots of things to work through. Presumably, you learned a lot along the way? 😅 

> I was thumbing through that file trying to learn more about it, and must have inadvertently added a row. Do you know how I would have done that? I tried fixing it in the file (it opened a spreadsheet) and didn't really see anything to change. I ultimately re-downloaded the file.

I don't really know what might have happened to add an extra row. The real advice I have for you here is to also open these files up in your text editor. CSV is a text-based format, and it's totally fine to open it up and edit it as plain text. 

(For very large files I'll use a spreadsheet editor, sure; but I'll sometimes also `head` and `tail` it from the command line to see what I'm working with; or `cat` again if it is reasonably sized.)

> Curious too: how did you know the CSV file had the extra line?

When I saw the error about nil and didn't notice anything obviously wrong with the code, I clicked into the CSV to browse what the data looked like. 

There's an expression if you haven't heard yet you'll hear eventually: garbage in, garbage out. It doesn't matter how good your code is if you're working with bad input! So sanity checking your input becomes a normal thing to think about and do.

And then since I was looking at it in the text editor and it's a small file I just visually noticed the line.

> BTW: I'll be finishing Chapter 3 tonight and probably will have that up tomorrow morning. Sorry I've fallen behind a bit! 

You don't owe an apology. This is your endeavor. I just happen to have free time. :)

**Comment by erikamaker** [comment]
Finally got through to the end of Chapter 3! I got a little preoccupied refactoring Bonecrawl and studying CSS / HTML the last week. I definitely learned a lot along the way, especially in getting that CSV reading program working. Your input was very helpful, and I appreciate that you only led me in the right direction after I exhausted the best efforts I could have made this early in my learning. I imagine that, as I learn more, checking files for "garbage" like you did with that data file will become second nature. 

I updated the rest of Chapter 3 notes and will be working through 4 this week. I'm also working on a TOP project. I have to try and contain myself-- the more I learn, the more I want to update my engine. It's getting to be a lot of fun, and less of a headache. I find myself knowing the solution to bugs so much quicker than before I began working through this text. 

Closing these two issues :-) Thank you!

**Comment by ianterrell** [comment]
> I have to try and contain myself-- the more I learn, the more I want to update my engine. It's getting to be a lot of fun, and less of a headache. I find myself knowing the solution to bugs so much quicker than before I began working through this text.

That's super awesome and amazing progress!
