### ISSUE TITLE
Chapter 4 Notes Feedback 2

### ISSUE THREAD

**Issue by ianterrell** [erikamaker/pickaxe#7]
## Digging

> I'm a little unclear about why this is an advantage. Doesn't Array also return nil if the element doesn't exist? I tested below to make sure I wasn't wrong about that, so I must be misinterpreting the text?

The difference and advantage comes with single level versus multiple level accessing.

```ruby
x = [[:a]]

x[0][0] #=> :a
x.dig(0, 0) #=> :a

x[1] #=> nil
x[1][0] # (irb):7:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
x.dig(1, 0) #=> nil
```

```ruby
y = { a: { b: :c } }

y[:a][:b] #=> :c
y.dig(:a, :b) #=> :c

y[:d] #=> nil
y[:d][:b] # (irb):16:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
y.dig(:d, :b) #=> nil
```

## Word Frequency

> the pattern /[\w']+/ to match word characters

Yay, regular expressions! I think I showed you once, but it's always fun to play with and visualize them at rubular.com — put the regex in, paste in some input, look at what matches.

<img width="983" alt="Screenshot 2023-03-23 at 1 43 40 PM" src="https://user-images.githubusercontent.com/54963/227295039-1e92ca73-f555-41c1-ae34-0cca34026d3f.png">

> the text does it this way, but I believe I can just use `.key?(next_word)` for the same effect.

You don't have to believe, you can double check. :)

It looks like there is one main implementation with three aliases on `Hash`:

https://ruby-doc.org/3.2.1/Hash.html#method-i-has_key-3F

<img width="540" alt="Screenshot 2023-03-23 at 1 46 40 PM" src="https://user-images.githubusercontent.com/54963/227296500-b074061c-dc8a-4e50-9af5-d99978de5251.png">

I had not thought about `member?` and did not know it was an alias for `include?`, which I usually use only to check for array membership. So I learned something.

> However, the text says there's an "tidier" way.

Presumably this was with the default value of `0` from `Hash.new(0)`. That is better. I usually end up doing a two liner in similar situations:

```ruby
hash[key] ||= 0
hash[key] += 1
```

I use the default values some, and I'll keep an eye out in my code for more use cases.

---

Looks like you're learning tons! Great progress.

**Comment by ianterrell** [comment]
Also, I was curious to see if ChatGPT would be helpful here. This thing is so neat.

<img width="813" alt="Screenshot 2023-03-23 at 3 23 14 PM" src="https://user-images.githubusercontent.com/54963/227326063-0834375e-ed63-4f1e-b681-d9494887f818.png">

**Comment by erikamaker** [comment]
> The difference and advantage comes with single level versus multiple level accessing.

Thank you (and thank you, shiny language model) for helping me grasp that concept better. It feels a little above me still, but I think practical application will help. I'll keep an eye out when I start using `dig` in my programs. 

Speaking of practical application: I do use ChatGPT. Google or the Ruby documentation is usually my first and last stop. If I want to dive deeper, sometimes I'll ask ChatGPT to break a concept down by walking me through an example, and I ask questions along the way. 

> Yay, regular expressions! I think I showed you once, but it's always fun to play with and visualize them at rubular.com — put the regex in, paste in some input, look at what matches.

I thought the syntax looked familiar! 😄 

> It looks like there is one main implementation with three aliases on Hash:

I've seen all three of those on a Hash at some point, and wondered why there were multiple ways to write it. I'll have to research the differences. 

Thank you for your feedback! ^-^ Closing this issue.
