### ISSUE TITLE
Ch 4 — map vs each

### ISSUE THREAD

**Issue by ianterrell** [erikamaker/pickaxe#8]
Super brief — and please tell me if I start to annoy or this becomes unhelpful — 

The sort of folk wisdom around each vs map is:

- do you want to _do_ something for each item?
- or do you want to _have_ something new from each item?

Generally if you don't want to keep the results around you don't want to use map — that will allocate new arrays or collections and increase memory usage, etc. If you just want to _do_ something with them, use each. But if you want the results for later (or a subsequent step), then you want map.

Often the memory usage doesn't really matter concretely, and then it comes down to semantics and how the code communicates the programmer's intent. If you see `each` you can stop thinking about those values when it's done; if you see `map` you know they want to be transformed into something new for subsequent use.

**Comment by erikamaker** [comment]
I appreciate it! I am always glad for your input. It's helping me level up faster than I could on my own. So, for a simple `each` block, each element has a block executed on it and the value is returned. With `map`, a new collection is actually created using each element that had executed a block on it. But neither of these methods actually mutate the original collection, they both perform a block on each element, it's just how that return value is stored differs. Is that right?

**Comment by ianterrell** [comment]
> So, for a simple each block, the elements have a block executed on it, and the value is returned.

If by the value you mean the original collection; yes. Back to our old friend `object_id`...

```ruby
x             # => [1, 2]
x.object_id   # => 59840
x.each{|a|a}  # => [1, 2]
x.each{|a|a}.object_id  # => 59840
x.each{|a|a}.object_id  # => 59840
x.each{|a|a}.object_id  # => 59840
x.map{|a|a}   # => [1, 2]
x.map{|a|a}.object_id   # => 252580
x.map{|a|a}.object_id   # => 303900
x.map{|a|a}.object_id   # => 309080
```

With `each` you're not creating a new collection; with `map` you are.

But yep — as always, you've got it.
